#
# Define ALL deploy hosts grouped by app.
#
# NOTE you CANNOT define same hosts for multiple app or ansible will read vars incorrectly.
#

all:
  children:
    api:
      hosts:
        api.local.highdax.com:
    config:
      hosts:
        config.local.highdax.com:
    hd-cold-wallet:
      hosts:
        hd-cold-wallet.local.highdax.com:
    hd-hot-wallet:
      hosts:
        hd-hot-wallet.local.highdax.com:
    manage:
      hosts:
        manage.local.highdax.com:
    mq:
      hosts:
        mq.local.highdax.com:
    notification:
      hosts:
        notification.local.highdax.com:
    sequence:
      hosts:
        sequence.local.highdax.com:
    quotation:
      hosts:
        quotation.local.highdax.com:
    spot-clearing:
      hosts:
        spot-clearing.local.highdax.com:
    spot-match:
      hosts:
        spot-match.local.highdax.com:
    www:
      hosts:
        static.local.highdax.com:
      vars:
        lua_dns_ip: 8.8.8.8
        lua_rate_limit: 10
        lua_rate_burst: 15
        lua_redis_host: 127.0.0.1
    ui:
      hosts:
        ui.local.highdax.com:
