#
# Define ALL deploy hosts grouped by app.
#
# NOTE you CANNOT define same hosts for multiple app or ansible will read vars incorrectly.
#

all:
  children:
    api:
      hosts:
        api.highdax.com:
    config:
      hosts:
        config.highdax.com:
    hd-cold-wallet:
      hosts:
        hd-cold-wallet.highdax.com:
    hd-hot-wallet:
      hosts:
        hd-hot-wallet.highdax.com:
    manage:
      hosts:
        manage.highdax.com:
    mq:
      hosts:
        mq.highdax.com:
    notification:
      hosts:
        notification.highdax.com:
    sequence:
      hosts:
        sequence.highdax.com:
    quotation:
      hosts:
        quotation.highdax.com:
    spot-clearing:
      hosts:
        spot-clearing.highdax.com:
    spot-match:
      hosts:
        spot-match.highdax.com:
    www:
      hosts:
        static.highdax.com:
      vars:
        lua_dns_ip: 8.8.8.8
        lua_rate_limit: 10
        lua_rate_burst: 15
        lua_redis_host: 127.0.0.1
    ui:
      hosts:
        ui.highdax.com:
