# API configuration:

server:
  port: 8001

crypto:
  setting:
    load-symbols-from: db
  api:
    request:
      maxRequestBodySize: 8192
  # upload settings:
  storage:
    type: s3
    s3:
      region: ${S3_REGION:ap-northeast-1}
      bucket: ${S3_BUCKET:sample}
      aws-api-key: ${S3_API_KEY:NA}
      aws-api-secret: ${S3_API_SECRET:NA}

# datasource configuration:
spring:
  ex-rw-datasource:
    url: jdbc:mysql://${DB_EX_RW_HOST:${DB_RW_HOST:localhost}}/ex?useSSL=false&characterEncoding=utf8
    username: ${DB_EX_RW_USERNAME:ex_rw}
    password: ${DB_EX_RW_PASSWORD:ex_rw_password}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: HikariCP
      auto-commit: false
      connection-timeout: 5000
      validation-timeout: 3000
      max-lifetime: 600000
      maximum-pool-size: 50
      minimum-idle: 2
  ex-ro-datasource:
    url: jdbc:mysql://${DB_EX_RO_HOST:${DB_RO_HOST:localhost}}/ex?useSSL=false&characterEncoding=utf8
    username: ${DB_EX_RO_USERNAME:ex_ro}
    password: ${DB_EX_RO_PASSWORD:ex_ro_password}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: HikariCP
      auto-commit: false
      connection-timeout: 5000
      validation-timeout: 3000
      max-lifetime: 600000
      maximum-pool-size: 50
      minimum-idle: 2
