# native configuration (for local development):

crypto:
  order:
    features:
      enable-fill-or-kill: true
      enable-immediate-or-cancel: true
      enable-post-only: true
      enable-hidden: true
      enable-stop: true
      enable-stop-limit: true
      enable-trailing-stop: true
  setting:
    fee:
      always-charge-quote: true

# logging config:
logging:
  level:
    com.itranswarp.warpdb.WarpDb: DEBUG
