# HDHotWallet configuration:

server:
  port: 8009

crypto:
  setting:
    load-symbols-from: api
    load-symbols-url: /wallet/trades
  wallet:
    cold:
      # cold wallet address, default to "http://localhost:8007":
      endpoint: ${COLD_ENDPOINT:http://localhost:8007}
      # api key / secret used for accessing cold wallet:
      api-key: ${COLD_API_KEY:ColdWalletInternalKey}
      api-secret: ${COLD_API_SECRET:ColdWalletInternalSecret}
    api:
      # API server address, default to "http://localhost:8001":
      endpoint: ${API_ENDPOINT:http://localhost:8001}
    #
    # Node configuration:
    #
    # BTC node:
    btc:
      # set enabled:
      enabled: ${BLOCKCHAIN_BTC_ENABLED:true}
      # rpc end point:
      endpoint: ${BLOCKCHAIN_BTC_ENDPOINT:http://btc.blockchain.highdax.com}
      # scan from block height:
      start-block-height: 548740
      # scan from block hash:
      # IMPORTANT: the hash string MUST be quoted:
      start-block-hash: "000000000000000000163620a604352b80bdf0ee0576fd610fb8df8ec1ad6931"
    # ETH node:
    eth:
      # set enabled:
      enabled: ${BLOCKCHAIN_ETH_ENABLED:true}
      # rpc end point:
      endpoint: ${BLOCKCHAIN_ETH_ENDPOINT:http://eth.blockchain.highdax.com}
      # scan from block height:
      start-block-height: 6642570
      # scan from block hash:
      # IMPORTANT: the hash string MUST be quoted:
      start-block-hash: "0xdd2b3f45597a3a55a65182f4f86315b405e8f3a5f3344fe0bee88d274082cd15"
    # USDT node:
    usdt:
      enabled: ${BLOCKCHAIN_OMNI_ENABLED:false}
      endpoint: ${BLOCKCHAIN_OMNI_ENDPOINT:http://omni.blockchain.highdax.com}
    # ETC node:
    etc:
      enabled: ${BLOCKCHAIN_ETC_ENABLED:false}
      endpoint: ${BLOCKCHAIN_ETC_ENDPOINT:http://etc.blockchain.highdax.com}
    # LTC node:
    ltc:
      enabled: ${BLOCKCHAIN_LTC_ENABLED:false}
      endpoint: ${BLOCKCHAIN_LTC_ENDPOINT:http://ltc.blockchain.highdax.com}
    # QTUM node:
    qtum:
      enabled: ${BLOCKCHAIN_QTUM_ENABLED:false}
      endpoint: ${BLOCKCHAIN_QTUM_ENDPOINT:http://qtum.blockchain.highdax.com}

# datasource configuration:
spring:
  hd-rw-datasource:
    url: jdbc:mysql://${DB_HW_RW_HOST:${DB_RW_HOST:localhost}}/hd?useSSL=false&characterEncoding=utf8
    username: ${DB_HD_RW_USERNAME:hd_rw}
    password: ${DB_HD_RW_PASSWORD:hd_rw_password}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: HikariCP
      auto-commit: false
      connection-timeout: 5000
      validation-timeout: 3000
      max-lifetime: 600000
      maximum-pool-size: 10
      minimum-idle: 2
