#
# Define ALL deploy hosts grouped by app.
#
# NOTE you CANNOT define same hosts for multiple app or ansible will read vars incorrectly.
#

all:
  children:
    api:
      hosts: # 8-15
        172.18.0.8:
        172.18.0.9:
    config:
      hosts: # 16
        172.18.0.16:
    hd-cold-wallet:
      hosts:
        172.18.7.8: # subnet .7
    hd-hot-wallet:
      hosts:
        172.18.8.8: # subnet .8
    manage:
      hosts: # 20
        172.18.0.20:
    mq:
      hosts: # 28-29
        172.18.0.28:
    notification:
      hosts: # 32-89
        172.18.0.32:
        172.18.0.33:
        172.18.0.34:
        172.18.0.35:
    sequence:
      hosts: # 90-91
        172.18.0.90:
        172.18.0.91:
    quotation:
      hosts: # 96-97
        172.18.0.96:
    spot-clearing:
      hosts: # 100-109
        172.18.0.100:
        172.18.0.101:
    spot-match:
      hosts: # 110-113
        172.18.0.110:
        172.18.0.111:
    www:
      hosts: # 120-127
        172.18.0.120:
      vars:
        lua_dns_ip: 172.18.0.2 # <- change to AWS internal DNS
        lua_rate_limit: 10
        lua_rate_burst: 15
        lua_redis_host: 127.0.0.1 # <- change to AWS elastic cache domain
    ui:
      hosts: # 128-159
        172.18.0.128:
        172.18.0.129:
        172.18.0.130:
        172.18.0.131:
