# update symbol link /srv/cryptoexchange/{{ app.name }} -> /srv/cryptoexchange/{{ app.name }}-{{ app.timestamp }}

---

- name: remove old symbol link /srv/cryptoexchange/{{ app.name }}
  file:
    path: /srv/cryptoexchange/{{ app.name }}
    state: absent

- name: create symbol link /srv/cryptoexchange/{{ app.name }} -> /srv/cryptoexchange/{{ app.name }}-{{ app.timestamp }}
  file:
    src: /srv/cryptoexchange/{{ app.name }}-{{ app.timestamp }}
    dest: /srv/cryptoexchange/{{ app.name }}
    state: link

- name: remove old deployed targets from /srv/cryptoexchange/{{ app.name }}-*
  shell: "ls -td -1 {{ app.name }}-* | tail -n +11"
  args:
    chdir: /srv/cryptoexchange/
  register: to_be_deleted

- name: will remove old deployed targets
  debug: msg="{{ item }}"
  with_items: "{{ to_be_deleted.stdout_lines }}"

- name: actually remove old deployed jars
  file:
    name: /srv/cryptoexchange/{{ item }}
    state: absent
  with_items: "{{ to_be_deleted.stdout_lines }}"
